### PR TITLE
15625 bug update pipedrive components to latest sdk api version

### LINKED ISSUE #15625: [BUG] Update Pipedrive components to latest SDK / API version
**Describe the bug**
Current Pipedrive components are using an old SDK version ([see here](https://github.com/PipedreamHQ/pipedream/pull/15624)). We should either update the code to use the latest SDK version or use the v2 API using `@pipedream/platform axios`

[Node.js SDK](https://github.com/pipedrive/client-nodejs)
[API v2](https://pipedrive.readme.io/docs/pipedrive-api-v2)
[API v2 migration guide](https://pipedrive.readme.io/docs/pipedrive-api-v2-migration-guide)

### PR DESCRIPTION
**Pull request by luancazarine**
Resolves #15625

## Summary by CodeRabbit

- **New Features**
  - Introduced new instant event sources for added and updated deals and persons.
  - Added new properties and improved functionality for activity, note, deal, organization, and person actions.
  - Enhanced error handling across various actions for clearer reporting.

- **Refactor**
  - Standardized property naming, parsing, and error handling for a more consistent experience.
  - Unified pagination using a cursor-based approach for smoother data navigation.

- **Chores**
  - Upgraded platform dependencies and removed deprecated configurations to enhance overall performance.

### CODE REVIEW

File: components/pipedrive/actions/add-activity/add-activity.mjs [hunk 1]
```diff
@@ -76,148 +43,159 @@ export default {
...
+      description: "ID of the organization this activity will be associated with",
     },
-    organizationId: {
+    projectId: {
       propDefinition: [
         pipedriveApp,
-        "organizationId",
+        "projectId",
       ],
       description: "ID of the organization this activity will be associated with",
```
Comment (michelle0927) [inline components/pipedrive/actions/add-activity/add-activity.mjs:64]: The description should be for `projectId`, not organization.
```suggestion
```

File: components/pipedrive/actions/add-activity/add-activity.mjs [hunk 2]
```diff
@@ -76,148 +43,159 @@ export default {
...
+    location: {
+      type: "object",
+      label: "Location",
+      description: "The address of the activity. Pipedrive will automatically check if the location matches a geo-location on Google maps.",
+      optional: true,
+    },
+    participants: {
+      type: "string[]",
+      label: "Participants",
+      description: "List of multiple persons (participants) this activity will be associated with. If omitted, single participant from `person_id` field is used. It requires a structure as follows: `[{\"person_id\":1,\"primary_flag\":true}]`",
```
Comment (michelle0927) [inline components/pipedrive/actions/add-activity/add-activity.mjs:105]: The example `participants` structure should match the structure in the component.
```suggestion
      description: "List of multiple persons (participants) this activity will be associated with. If omitted, single participant from `person_id` field is used. It requires a structure as follows: `[{\"person_id\":1,\"primary\":true}]`",
```

**Review by michelle0927 — CHANGES_REQUESTED** [review]
I think we can leave out the `yarn.lock` file from this PR.

Also, once it's published, remember to ask Danny to unpublish/redirect the component keys that have been removed/changed.
- pipedrive-new-deal -> pipedrive-new-deal-instant
- pipedrive-new-person -> pipedrive-new-person-instant
- pipedrive-updated-deal -> pipedrive-updated-deal-instant
- pipedrive-updated-person -> pipedrive-updated-person-instant

**Review by michelle0927 — APPROVED** [review]
LGTM!

**Review by michelle0927 — APPROVED** [review]
