### PR TITLE
[FIX] Dedup key in Outlook Shared Email Received causing events to be…

### LINKED ISSUE #18884: [BUG] Dedup key in Outlook Shared Email Received causing events to be dropped
**Describe the bug**
ConversationID is used as the dedup ID for Shared Email Received, causing any follow up emails/emails in threads to not be received properly. Conversation ID identifies an email thread in outlook - not an individual email. 

See here: https://github.com/PipedreamHQ/pipedream/blob/36a8917969982afaa545f7577f28f3c0dde4466c/components/microsoft_outlook/sources/new-email-in-shared-folder/new-email-in-shared-folder.mjs#L70

[This is why item.id is used in the receive mail api](https://github.com/PipedreamHQ/pipedream/blob/36a8917969982afaa545f7577f28f3c0dde4466c/components/microsoft_outlook/sources/new-email/new-email.mjs#L47)

**To Reproduce**

1. Send email to shared inbox
2. Reply to that email 
3. Note that the reply is not properly emitted 

**Expected behavior**
New emails in the same email thread should be emitted

**Screenshots**

Image

Image

Image

### PR DESCRIPTION
**Pull request by jcortes**
… dropped

## WHY

Resolves #18884

## Summary by CodeRabbit

* **Bug Fixes**
  * "New email in shared folder" events now order and filter by sent time, persist sent time for progress tracking, include consistent event timestamps, use the message ID for events, and display email subjects in summaries.

* **Chores**
  * Updated Microsoft Outlook component to v1.7.4 and the "New email in shared folder" source to v0.0.4.

### CODE REVIEW

**Review by GTFalcao — DISMISSED** [review]

**Comment by vunguyenhung** [comment]
### For Integration QA:
- Source Test Report: https://www.notion.so/BUG-Dedup-key-in-Outlook-Shared-Email-Received-causing-events-to-be-dropped-Sources-2a0bf548bb5e814dae86e49c9e78408e

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check test reports below for more information:
- [BUG] Dedup key in Outlook Shared Email Received causing events to be dropped - Sources: https://www.notion.so/BUG-Dedup-key-in-Outlook-Shared-Email-Received-causing-events-to-be-dropped-Sources-2a0bf548bb5e814dae86e49c9e78408e

**Comment by jcortes** [comment]
Hi @vunguyenhung I've just pushed the fix, please try again! thanks!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check test reports below for more information:
- [BUG] Dedup key in Outlook Shared Email Received causing events to be dropped - Sources: https://www.notion.so/BUG-Dedup-key-in-Outlook-Shared-Email-Received-causing-events-to-be-dropped-Sources-2a0bf548bb5e814dae86e49c9e78408e

File: components/microsoft_outlook/sources/new-email-in-shared-folder/new-email-in-shared-folder.mjs [hunk 1]
```diff
@@ -61,15 +61,18 @@ export default {
...
 
       for (const item of responseArray.reverse()) {
+        const ts = Date.parse(item.sentDateTime);
         this.$emit(
           item,
           {
-            id: item.conversationId,
-            summary: `A new email with id: "${item.conversationId}" was received!`,
-            ts: item.createdDateTime,
+            id: `${item.conversationId}-${ts}`,
```
Comment (alexpareto) [inline components/microsoft_outlook/sources/new-email-in-shared-folder/new-email-in-shared-folder.mjs]: why rely on conversation ID + timestamp instead of message ID?

**Comment by jcortes** [comment]
Hi @vunguyenhung it seems like you are refering to the conversation/thread in an email message which I don't think would be the right approach to that source component since the main message might have a lot of nested messages. So because the design of the endpoint list only the ones in the shared folder it would not be a good idea to make requests on the each nested message. I hope it makes sense!

File: components/microsoft_outlook/sources/new-email-in-shared-folder/new-email-in-shared-folder.mjs (hunk 1 above)
Comment (jcortes) [reply components/microsoft_outlook/sources/new-email-in-shared-folder/new-email-in-shared-folder.mjs]: Hi @alexpareto I've just changed it to `item.id`

**Comment by alexpareto** [comment]
> Hi @vunguyenhung it seems like you are refering to the conversation/thread in an email message which I don't think would be the right approach to that source component since the main message might have a lot of nested messages. So because the design of the endpoint list only the ones in the shared folder it would not be a good idea to make requests on the each nested message. I hope it makes sense!

I do think that the event should output a new event when replies are received to the original thread. 

For example:
john@example.com 
bill@sharedinbox.com 

1. Email 1: john@example.com emails bill@sharedinbox.com (triggers event) 
2. Email 2: bill@shareindbox.com replies back to john@example.com (no event, same conversation id) 
3. Email 3: john@example.com replies back to bill@sharedinbox.com (triggers event, same conversation id, different item id)

That said, with the different item.id I think this should work.

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release!

Test reports
- [BUG] Dedup key in Outlook Shared Email Received causing events to be dropped - Sources: https://www.notion.so/BUG-Dedup-key-in-Outlook-Shared-Email-Received-causing-events-to-be-dropped-Sources-2a0bf548bb5e814dae86e49c9e78408e
