### PR TITLE
Confluence adjustments

### LINKED ISSUE #19217: [ACTION] Add body-format to Confluence - Get Page by ID
**Is there a specific app this action is for?**

Atlassian Confluence

**Please provide a link to the relevant API docs for the specific service / operation.**

https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-page/#api-pages-id-get

`body-format`
> The content format types to be returned in the body field of the response. If available, the representation will be available under a response field of the same name under the body field.
> Valid values: storage, atlas_doc_format, view, export_view, anonymous_export_view, styled_view, editor

NOTE: the "Get Pages" action has a bug where the wrong property name is provided for "body-format". Be sure to use the correct property name: https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-page/#api-pages-get

Currently, the actions does not include any search parameters/arguments. Other important parameters include:

`include-properties`
> Includes content properties associated with this page in the response. The number of results will be limited to 50 and sorted in the default sort order. A meta and _links property will be present to indicate if more results are available and a link to retrieve the rest of the results.

### LINKED ISSUE #19219: [BUG] "Confluence - Get Pages" action passes incorrect `body-format` parameter name
**Describe the bug**

- "Confluence - Get Pages" passes `bodyFormat` instead of the expected `body-format` parameter name

**To Reproduce**

1. Use the Confluence - Get Pages action
2. Provide `atlas_doc_format` for Body Type
3. No `body` is returned

**Expected behavior**

Page body is returned in the specified format under the `body` property

**Additional context**

- https://github.com/PipedreamHQ/pipedream/blob/6845b857e86c307524f577adadbf02758390b4d3/components/confluence/actions/get-pages/get-pages.mjs#L70
- Confluence documentation: https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-page/#api-pages-get

### PR DESCRIPTION
**Pull request by GTFalcao**
Closes #19217 
Closes #19219 

## Summary by CodeRabbit

* **New Features**
  * Get Page by ID: add options for body format, draft retrieval, status filter, version selection, and custom additional options (supports JSON values).
  * Expanded body format choices for page-related actions.
  * Added JSON-aware utility to parse additional options.

* **Chores**
  * Removed subType parameter from page-listing actions.
  * Normalized request parameter keys for page-listing actions.
  * Multiple action and package version bumps (metadata only).

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: components/confluence/actions/get-page-by-id/get-page-by-id.mjs [hunk 1]
```diff
@@ -19,6 +21,47 @@ export default {
         "pageId",
       ],
     },
+    bodyFormat: {
+      type: "string",
+      label: "Body Format",
+      description: "The content format types to be returned in the `body` field of the response. If available, the representation will be available under a response field of the same name under the `body` field.",
+      optional: true,
+      options: BODY_FORMAT_FULL_OPTIONS,
+    },
```
Comment (michelle0927) [inline components/confluence/actions/get-page-by-id/get-page-by-id.mjs:30]: Is there a reason this doesn't use the `bodyFormat` prop from the app file?

Comment (GTFalcao) [reply components/confluence/actions/get-page-by-id/get-page-by-id.mjs:30]: No, thanks for making the update, it should've reused hte propDefinition and overridden only the options
