### PR TITLE
Fix Stripe actions errors using props with async options

### LINKED ISSUE #1853: [BUG] Stripe Create Invoice action fails with Cannot read property 'sdk' of undefined error
**Describe the bug**
When configuring the **Stripe** - **Create Invoice** action's **Customer ID** prop with structured mode enabled in a workflow on [pipedream](https://pipedream.com/), the UI shows the error: `UserError:bad options response for prop: customer` above the input field. The first line of the stack trace says `TypeError: Cannot read property 'sdk' of undefined`. See [this slack comment](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1635164618068000?thread_ts=1634885807.015600&cid=CPTJYRY5A).

**To Reproduce**
1. Go to https://pipedream.com/workflows
2. Click on "New +"
3. Click on "HTTP API" or "Schedule" Trigger
4. Click on "+" (Add a step)
5. Enter "Stripe" in the input field & click on "Stripe"
6. Enter "Create Invoice in the input field & click on "Create Invoice"
7. Select an account
8. See error

**Expected behavior**
An error should not appear. A dropdown list of customers or "No matching options." should appear when clicking on the input field below **Customer ID**.

**Screenshots**
stripeinvoice

**Additional context**
`this.stripe` is `undefined` in [`createOptionsMethod()`](https://github.com/PipedreamHQ/pipedream/blob/257ecbb6b2da3739affe60cca18237464b623a8e/components/stripe/stripe.app.js#L12) and in [`async options` functions](https://github.com/PipedreamHQ/pipedream/blob/257ecbb6b2da3739affe60cca18237464b623a8e/components/stripe/stripe.app.js#L182) in [`stripe.app.js`](https://github.com/PipedreamHQ/pipedream/blob/master/components/stripe/stripe.app.js).

### PR DESCRIPTION
**Pull request by js07**
Updates Stripe components to fix bugs in actions including "Cannot read property 'sdk' of undefined" error mentioned in #1853.

### Changelog

- Fix calling methods using `this.stripe`, which is `undefined` in `stripe.app.js`
- Fix trying to access component prop values in app file using `this.<prop>`
- Fix `options` and `default` properties of some component props

Fixes #1853

### CODE REVIEW

**Comment by dylburger** [comment]
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

File: components/stripe/actions/confirm-payment-intent/confirm-payment-intent.js [hunk 1]
```diff
@@ -28,6 +28,9 @@ module.exports = {
       propDefinition: [
         stripe,
         "payment_method",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/confirm-payment-intent/confirm-payment-intent.js:33]:
```suggestion
        ({ customer }) => ({
          customer,
        }),
```

File: components/stripe/actions/create-invoice-item/create-invoice-item.js [hunk 2]
```diff
@@ -26,12 +26,19 @@ module.exports = {
       propDefinition: [
         stripe,
         "subscription",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/create-invoice-item/create-invoice-item.js:31]:
```suggestion
        ({ customer }) => ({
          customer,
        }),
```

File: components/stripe/actions/create-invoice-item/create-invoice-item.js [hunk 3]
```diff
@@ -26,12 +26,19 @@ module.exports = {
...
       ],
     },
     invoice: {
       propDefinition: [
         stripe,
         "invoice",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+          subscription: configuredProps.subscription,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/create-invoice-item/create-invoice-item.js:41]:
```suggestion
        ({
          customer, subscription,
        }) => ({
          customer,
          subscription,
       }),
```

File: components/stripe/actions/create-invoice/create-invoice.js [hunk 4]
```diff
@@ -20,6 +20,9 @@ module.exports = {
       propDefinition: [
         stripe,
         "subscription",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/create-invoice/create-invoice.js:25]:
```suggestion
        ({ customer }) => ({
          customer,
        }),
```

File: components/stripe/actions/create-invoice/create-invoice.js [hunk 5]
```diff
@@ -50,6 +55,9 @@ module.exports = {
       propDefinition: [
         stripe,
         "payment_method",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/create-invoice/create-invoice.js:60]:
```suggestion
        ({ customer }) => ({
          customer,
        }),
```

File: components/stripe/actions/create-payment-intent/create-payment-intent.js [hunk 6]
```diff
@@ -27,6 +27,9 @@ module.exports = {
       propDefinition: [
         stripe,
         "currency",
+        (configuredProps) => ({
+          country: configuredProps.country,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/create-payment-intent/create-payment-intent.js:32]:
```suggestion
        ({ country }) => ({
          country,
        }),
```

File: components/stripe/actions/create-usage-record/create-usage-record.js [hunk 7]
```diff
@@ -23,20 +23,31 @@ module.exports = {
       "propDefinition": [
         stripe,
         "price",
+        () => ({
+          // Only `recurring` prices can be used to filter subscriptions
+          type: "recurring",
```
Comment (jcortes) [inline components/stripe/actions/create-usage-record/create-usage-record.js:28]: I would suggest setting this kind of fixed values in a `constants.js` file and references from it

File: components/stripe/actions/create-usage-record/create-usage-record.js [hunk 8]
```diff
@@ -23,20 +23,31 @@ module.exports = {
...
     },
     // Required to select subscription item
     subscription: {
       "propDefinition": [
         stripe,
         "subscription",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+          price: configuredProps.price,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/create-usage-record/create-usage-record.js:40]:
```suggestion
        ({
          customer, price,
        }) => ({
          customer,
          price,
        }),
```

File: components/stripe/actions/create-usage-record/create-usage-record.js [hunk 9]
```diff
@@ -23,20 +23,31 @@ module.exports = {
...
       ],
       "optional": false,
     },
     id: {
       "propDefinition": [
         stripe,
         "subscription_item",
+        (configuredProps) => ({
+          subscription: configuredProps.subscription,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/create-usage-record/create-usage-record.js:50]:
```suggestion
        ({ subscription }) => ({
          subscription,
        }),
```

File: components/stripe/actions/delete-invoice-item/delete-invoice-item.js [hunk 10]
```diff
@@ -19,6 +19,9 @@ module.exports = {
       propDefinition: [
         stripe,
         "invoice_item",
+        (configuredProps) => ({
+          invoice: configuredProps.invoice,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/delete-invoice-item/delete-invoice-item.js:24]:
```suggestion
        ({ invoice }) => ({
          invoice,
        }),
```

File: components/stripe/actions/list-invoices/list-invoices.js [hunk 11]
```diff
@@ -19,6 +19,10 @@ module.exports = {
       propDefinition: [
         stripe,
         "subscription",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+          price: configuredProps.price,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/list-invoices/list-invoices.js:25]:
```suggestion
       ({
         customer, price,
       }) => ({
          customer,
          price,
       }),
```

File: components/stripe/actions/retrieve-invoice-item/retrieve-invoice-item.js [hunk 12]
```diff
@@ -20,19 +20,29 @@ module.exports = {
       propDefinition: [
         stripe,
         "subscription",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/retrieve-invoice-item/retrieve-invoice-item.js:25]:
```suggestion
        ({ customer }) => ({
          customer,
        }),
```

File: components/stripe/actions/retrieve-invoice-item/retrieve-invoice-item.js [hunk 13]
```diff
@@ -20,19 +20,29 @@ module.exports = {
...
     },
     // Used to populate invoice item options
     invoice: {
       propDefinition: [
         stripe,
         "invoice",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+          subscription: configuredProps.subscription,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/retrieve-invoice-item/retrieve-invoice-item.js:36]:
```suggestion
       ({
         customer, subscription,
       }) => ({
          customer,
          subscription,
       }),
```

File: components/stripe/actions/retrieve-invoice-item/retrieve-invoice-item.js [hunk 14]
```diff
@@ -20,19 +20,29 @@ module.exports = {
...
       ],
     },
     id: {
       propDefinition: [
         stripe,
         "invoice_item",
+        (configuredProps) => ({
+          invoice: configuredProps.invoice,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/retrieve-invoice-item/retrieve-invoice-item.js:45]:
```suggestion
        ({ invoice }) => ({
          invoice,
        }),
```

File: components/stripe/actions/update-invoice-item/update-invoice-item.js [hunk 15]
```diff
@@ -21,19 +21,29 @@ module.exports = {
       propDefinition: [
         stripe,
         "subscription",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/update-invoice-item/update-invoice-item.js:26]:
```suggestion
        ({ customer }) => ({
          customer,
        }),
```

File: components/stripe/actions/update-invoice-item/update-invoice-item.js [hunk 16]
```diff
@@ -21,19 +21,29 @@ module.exports = {
...
     },
     // Used to populate invoice item options
     invoice: {
       propDefinition: [
         stripe,
         "invoice",
+        (configuredProps) => ({
+          customer: configuredProps.customer,
+          subscription: configuredProps.subscription,
+        }),
```
Comment (jcortes) [inline components/stripe/actions/update-invoice-item/update-invoice-item.js:37]:
```suggestion
        ({
          customer, subscription,
        }) => ({
          customer,
          subscription,
       }),
```

File: components/stripe/stripe.app.js [hunk 17]
```diff
@@ -2,15 +2,19 @@
 
 const stripe = require("stripe");
 
-const createOptionsMethod = (collectionOrFn, keysOrFn) => async function ({ prevContext }) {
+const createOptionsMethod = (collectionOrFn, keysOrFn) => async function ({
```
Comment (jcortes) [inline components/stripe/stripe.app.js:5]: I would recommend `/** jsdoc */` this function since it abstracts a few things in it IMO. But I totally understand if you don't document it since it will be out of scope I guess.

File: components/stripe/stripe.app.js [hunk 18]
```diff
@@ -2,15 +2,19 @@
...
+  prevContext, ...opts
+}) {
+  const { nextPageToken: pageToken } = prevContext;
```
Comment (jcortes) [inline components/stripe/stripe.app.js:8]: I would set a variable name like
```suggestion
  const { starting_after } = prevContext;
```

File: components/stripe/stripe.app.js [hunk 19]
```diff
@@ -24,14 +28,16 @@ const createOptionsMethod = (collectionOrFn, keysOrFn) => async function ({ prev
     }));
   }
 
-  let nextPageToken = null;
+  let nextPageToken;
```
Comment (jcortes) [inline components/stripe/stripe.app.js:31]: And I think you don't need to set again this variable as `undefined` since the loop will stop once `options` is empry right?

File: components/stripe/stripe.app.js [hunk 20]
```diff
@@ -240,14 +270,14 @@ module.exports = {
...
       label: "Country",
-      description: "Two-letter ISO country code, in lowercase",
-      options: createOptionsMethod("countrySpecs", function (id) {
+      description: "Two-letter ISO country code",
+      options: createOptionsMethod("countrySpecs", function (obj) {
         return {
-          value: id,
-          label: id,
+          value: obj.id,
+          label: obj.id,
```
Comment (jcortes) [inline components/stripe/stripe.app.js:277]:
```suggestion
     options: createOptionsMethod("countrySpecs", function ({ id }) {
        return {
          value: id,
          label: id,
```

**Review by jcortes — CHANGES_REQUESTED** [review]
It looks good to me. The issue was fixed. In addition to that I would also recommend pointing out the API docs on each action's `description` but that also can be out of scope.

File: components/stripe/stripe.app.js (hunk 19 above)
Comment (js07) [reply components/stripe/stripe.app.js:31]: I'm not sure, but that makes sense that `async options` would stop being called once the returned `options` array is empty. What would you suggest changing?

Comment (jcortes) [reply components/stripe/stripe.app.js:31]: ok you just need to assign again the `starting_after` with last value and that would do it

**Review by jcortes — APPROVED** [review]
It looks great to me! Thanks 🙏

**Comment by dannyroosevelt** [comment]
When selecting a "customer ID" via async options dropdown, it looks like we're currently setting the label to `customer_name`, which in theory makes sense, but it exposes 2 issues:
1. Not every customer record contains a `customer_name`, so the UI kinda breaks: 
image
2. I can imagine some users might have many customers with overlapping names

So I think in this case we should instead set the label value to something like, 
`customer_name (if available) | customer_email | customer_id`

File: components/stripe/stripe.app.js [hunk 21]
```diff
@@ -51,26 +104,37 @@ module.exports = {
...
+      options: createOptionsMethod("customers", function ({
+        id, name, email,
+      }) {
+        return {
+          value: id,
+          label: [
+            name,
+            email,
+            id,
+          ].filter((v) => v).join(" | "),
```
Comment (js07) [inline components/stripe/stripe.app.js:116]: Addressing [this comment](https://github.com/PipedreamHQ/pipedream/pull/1859#issuecomment-974394222):
I changed the **Customer ID** option's label to
`customer_name (if available) | customer_email (if available) | customer_id`

For example:
- Customer with name, email, id:
`John Doe | email@example.com | cus_Jz4ErxGo9t1agg`
- Customer with without name:
`email@example.com | cus_Jz4ErxGo9t1agg`
- Customer without email:
`John Doe | cus_Jz4ErxGo9t1agg`
- Customer without name or email:
`cus_Jz4ErxGo9t1agg`

Is that what you had in mind @dannyroosevelt?

Comment (dannyroosevelt) [reply components/stripe/stripe.app.js:116]: yep -- I'm not sure if that's the most elegant way to display those data, but it's much improved from before. lgtm, thank you!

**Comment by dannyroosevelt** [comment]
@js07 thanks for adding $summary to the other stripe actions! I don't need to QA these changes, so you're good to merge whenever!
