### PR TITLE
[BUG] Clickup - List prop failed with error Rate Limit reached

### LINKED ISSUE #12940: [BUG] Clickup - `List` prop failed with error Rate Limit reached
**Describe the bug**
A customer is facing the `Rate Limit reached` error when fetching the `List` prop
image

In the code here, we observed that the list props fetch quite a lit of things concurrently, which might hit Clickup Rate Limit when the ammount of records are large
https://github.com/PipedreamHQ/pipedream/blob/5245d6c58564d9624edf7ceceb3e855dd4abfc0b/components/clickup/clickup.app.mjs#L55

**Expected behavior**
The List prop should show all lists

**Additional context**
Raised by a customer here: https://app.frontapp.com/open/msg_1okfu5mv?key=8APiTGqB-P3RSR4Ti_FHi1nFmMsvIrP-

### PR DESCRIPTION
**Pull request by jcortes**
## WHY

Refactored list props to filter by folder id dinamically as an alternative

Resolves #12940

## Summary by CodeRabbit

- **New Features**
	- Added a `listWithFolder` property to multiple actions, allowing users to filter by Folder ID.
	- Introduced `additionalProps` to enhance property management and dynamic functionality across several actions.

- **Version Updates**
	- Incremented version numbers for multiple actions from "0.0.7" to "0.0.8" (or higher) to signify new releases and enhancements.

- **Refactor**
	- Improved structure and modularity by using spread syntax to incorporate properties from the common module across various actions.
	- Streamlined the exported structure of several modules for better maintainability and integration.

### CODE REVIEW

File: components/clickup/actions/create-chat-view-comment/create-chat-view-comment.mjs [hunk 1]
```diff
@@ -71,15 +25,28 @@ export default {
...
       ],
       optional: true,
     },
+    listWithFolder: {
+      type: "boolean",
+      label: "List With Folder?",
+      description: "If `true`, the list will be filtered by Folder ID",
+      reloadProps: true,
+      optional: true,
+    },
```
Comment (GTFalcao) [inline components/clickup/actions/create-chat-view-comment/create-chat-view-comment.mjs:42]: Can `listWithFolder` be a propDefinition, or imported from a common file? Since it's being used across most of the actions and the label, description etc. are all duplicated

**Review by GTFalcao — COMMENTED** [review]
I left just one comment @jcortes, since it doesn't impact functionality I'll move it forward!

**Review by GTFalcao — APPROVED** [review]
