### PR TITLE
Exports messages that were not delivered

### LINKED ISSUE #201: Discord action: if we exceed the API rate limit, action should return messages we failed to send
It might make sense to separate the streams of output, for example in { stdout, stderr }.

### PR DESCRIPTION
**Pull request by andrewjschuang**
**Enhancement**
Messages that failed to be delivered are exported through the variable name `unsent`.

Resolves #201

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

File: components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs [hunk 1]
```diff
@@ -46,13 +46,21 @@ export default {
...
       username,
-    });
+    };
+
+    try {
+      // No interesting data is returned from Discord
+      await this.discordWebhook.sendMessage(params);
+      $.export("$summary", "Message sent successfully");
+    } catch (err) {
+      $.export("$summary", `${err}`);
```
Comment (js07) [inline components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs:62]: I think the [`$summary`](https://pipedream.com/docs/components/guidelines/#guidelines-patterns) should use plain language to summarize what happened. E.g., "Failed to send the message. See the `unsent` [export](https://pipedream.com/docs/components/api/#returning-data-from-steps) for the unsent message."?  
Typically a `$summary` isn't emitted when an action fails.

File: components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs [hunk 2]
```diff
@@ -46,13 +46,21 @@ export default {
...
+      $.export("unsent", params);
```
Comment (js07) [inline components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs:63]: Should the data for the `unsent` export be the user-configured prop values rather than the `params` object? If the `includeSentViaPipedream` prop is `true`, `content` is different from `this.message`. Emitting an object with the prop values instead would allow users to resend the message using those prop values.

File: components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs [hunk 3]
```diff
@@ -46,13 +46,21 @@ export default {
...
       threadID,
       username,
-    });
+    };
+
+    try {
+      // No interesting data is returned from Discord
+      await this.discordWebhook.sendMessage(params);
+      $.export("$summary", "Message sent successfully");
+    } catch (err) {
```
Comment (js07) [inline components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs:61]: Re-throw the caught `err` (or a [formatted error](https://github.com/PipedreamHQ/pipedream/blob/55236b3aa993cbcb545e245803d8654c6358b0a2/components/airtable/airtable.app.js#L71)) so the workflow job fails and the error gets sent to system notifications or the global error workflow?

**Review by js07 — COMMENTED** [review]
@andrewjschuang I made a few comments that apply to each of the actions.

File: components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs (hunk 1 above)
Comment (andrewjschuang) [reply components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs]: Addressed

File: components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs (hunk 2 above)
Comment (andrewjschuang) [reply components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs:59]: Addressed

File: components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs (hunk 3 above)
Comment (andrewjschuang) [reply components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs:58]: Addressed

File: components/discord_webhook/actions/send-message-with-file/send-message-with-file.mjs [hunk 4]
```diff
@@ -58,24 +66,19 @@ export default {
...
 
-    if (includeSentViaPipedream) {
-      if (typeof content !== "string") {
-        content = JSON.stringify(content);
-      }
-      content += `\n\n${this.getSentViaPipedreamText()}`;
+    try {
+      // No interesting data is returned from Discord
+      await this.discordWebhook.sendMessageWithFile({
+        ...params,
```
Comment (js07) [inline components/discord_webhook/actions/send-message-with-file/send-message-with-file.mjs:72]: I think we ideally shouldn't pass the prop values (in [`params`](https://github.com/PipedreamHQ/pipedream/blob/0bf71aa27a8649d22b464be6331560fc477b9a75/components/discord_webhook/actions/send-message-with-file/send-message-with-file.mjs#L51-L59)) that aren't used by `sendMessageWithFile` to `sendMessageWithFile`, to make the code more easily understood. (Also applies to the other actions)

Idea/suggestion:
- Include only params used by `sendMessageWithFile` in `params`
- To export the [user input props](https://pipedream.com/docs/components/api/#user-input-props) on failure (as the message), create a method in `send-message-common.mjs` that gets the user input props

For example:
```js
  // `send-message-common.mjs`
  methods: {
    getUserInputProps(omit = [
      "discordWebhook",
    ]) {
      return Object.keys(this)
        .filter((k) => typeof this[k] !== "function" && !omit.includes(k))
        .reduce((props, key) => {
          props[key] = this[key];
          return props;
        }, {});
    },
```
```js
    } catch (err) {
      const unsentMessage = this.getUserInputProps();
      $.export("unsent", unsentMessage);
      throw err;
    }
```

File: components/discord_webhook/actions/send-message-common.mjs [hunk 5]
```diff
@@ -39,6 +39,14 @@ export default {
     },
   },
   methods: {
+    appendPipedreamText(message) {
```
Comment (js07) [inline components/discord_webhook/actions/send-message-common.mjs:42]: I like moving the logic of this function to the common file so it can be reused 👍.

**Review by js07 — COMMENTED** [review]
@andrewjschuang I made a comment about removing unused params passed to the `this.discordWebhook.sendMessage` methods, but otherwise it looks good to me.

File: components/discord_webhook/actions/send-message-with-file/send-message-with-file.mjs (hunk 4 above)
Comment (andrewjschuang) [reply components/discord_webhook/actions/send-message-with-file/send-message-with-file.mjs]: Addressed

**Comment by dannyroosevelt** [comment]
@js07 @andrewjschuang any thoughts on how to test this? I'm inclined to just publish since it seems pretty low risk.

**Comment by andrewjschuang** [comment]
> @js07 @andrewjschuang any thoughts on how to test this? I'm inclined to just publish since it seems pretty low risk.

Yeah, I tested it by looping messages until discord threw an rate limiting error

**Comment by js07** [comment]
> @js07 @andrewjschuang any thoughts on how to test this? I'm inclined to just publish since it seems pretty low risk.

I tested the sources by adding code to throw an error in the [`try` block](https://github.com/andrewjschuang/pipedream/blob/d761308ae3e09f5a33ca885d46c64fece7b9862d/components/discord_webhook/actions/send-message/send-message.mjs#L22). They all worked for me.

send-message-error
