### PR TITLE
Fix Google Drive & Sheets sources failing to emit events for shared drive files

### LINKED ISSUE #2345: [BUG] Google Drive - Changes to Specific Files source fails to emit events for shared drives
**Describe the bug**
No events are emitted by the Google Drive **Changes to Specific Files** source when I make a change to a file in a shared drive.

**To Reproduce**
1. Go to https://pipedream.com/sources
2. Click on 'New+' -> 'Google Drive' -> 'Changes to Specific Files'
3. Click on the 'Google Drive Account' dropdown -> click on an account
4. Click on '+ Drive' -> Drive dropdown -> a shared drive
5. Click on '+ Files' -> Files dropdown -> a file
6. Click on 'Create Source'
7. Wait until the page redirects
8. Make a change to the selected file in the shared drive
9. Wait a few minutes
10. Return to page for the source. See no events in the "Events" tab.

**Expected behavior**
Within a few minutes of making a change to the file, an event appears in the "Events" tab for the source.

**Additional context**
According to the Google Drive API docs on the ["Files: watch" endpoint](https://developers.google.com/drive/api/v3/reference/files/watch), "a change to a shared drive file won't create a notification". The **Changes to Specific Files** source currently uses that endpoint to watch for file changes.

Slack thread: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1646080449712359

### PR DESCRIPTION
**Pull request by js07**
**Changes**
~~Adds support for shared drive files in Google Drive & Sheets sources that watch for changes to specific files~~

~~Conditionally subscribes to changes using the Google Drive API's [changes: watch](https://developers.google.com/drive/api/v3/reference/changes/watch) endpoint, when the `drive` prop is a shared drive~~

- Adds new Google Sheets & Google Drive event sources to support watching for changes to specific files in a shared drive (using the [changes: watch](https://developers.google.com/drive/api/v3/reference/changes/watch) endpoint to subscribe to all changes in a drive)
- Refactors Google Sheets & Drive sources to reuse common logic in each pair of "My Drive" / "Shared Drive" sources

New sources:
- Google Drive **Changes to Specific Files (Shared Drive)**
- Google Sheets **New Row Added (Shared Drive, Instant)**
- Google Sheets **New Updates (Shared Drive, Instant)**
- Google Sheets **New Worksheet (Shared Drive, Instant)**

Updated sources:
- Google Drive **Changes to Specific Files**
- Google Sheets **New Row Added (Instant)**
- Google Sheets **New Updates (Instant)**
- Google Sheets **New Worksheet (Instant)**

**Issue**
Some Google Drive & Sheets sources created subscriptions using the [files: watch](https://developers.google.com/drive/api/v3/reference/files/watch) endpoint (to watch for changes to specific files), which does not create notifications for shared drive files.

**Comments**:
~~Would separate (Shared Drive) sources be preferable for each of the affected sources, since the source behaves differently when watching a shared drive (more invocations)?~~
*Created separate (Shared Drive) sources for each of the sources affected by #2345.

Fixes #2345

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

File: components/google_drive/sources/changes-to-specific-files/changes-to-specific-files.mjs [hunk 1]
```diff
@@ -65,14 +47,15 @@ export default {
...
       // headers, allowing us to look up the watched resource.
-      let subscriptions = this.db.get("subscriptions") || {};
+      let subscriptions = this._getSubscriptions() || {};
 
-      for (const fileID of this.files) {
+      const files = this.files;
+      for (const fileID of files) {
         const {
           expiration,
           resourceId,
```
Comment (michelle0927) [inline components/google_drive/sources/changes-to-specific-files/changes-to-specific-files.mjs:61]: This hook should probably use `this.googleDrive.activateFileHook()` instead of `this.googleDrive.watchFile()`
```
        const {
          expiration,
          resourceId,
        } = await this.googleDrive.activateFileHook(
          channelID,
          this.http.endpoint,
          fileID,
        );
```

File: components/google_sheets/sources/common/http-based/base.mjs [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+    http: "$.interface.http",
+    timer: {
+      label: "Push notification renewal schedule",
+      description:
+        "The Google Drive API requires occasionally renewal of push notification subscriptions. **This runs in the background, so you should not need to modify this schedule**.",
+      type: "$.interface.timer",
+      static: {
+        intervalSeconds: WEBHOOK_SUBSCRIPTION_RENEWAL_SECONDS,
+      },
+    },
```
Comment (michelle0927) [inline components/google_sheets/sources/common/http-based/base.mjs:40]: Since `sheetID` is used in all the components that use this `base.mjs`, we could put it as a prop in `base.mjs`.
```suggestion
      type: "$.interface.timer",
      static: {
        intervalSeconds: WEBHOOK_SUBSCRIPTION_RENEWAL_SECONDS,
      },
    },
    sheetID: {
        propDefinition: [
          googleSheets,
          "sheetID",
          (c) => ({
            driveId: this.getDriveId(c.watchedDrive),
          }),
        ],
     },
```

File: components/google_sheets/sources/common/http-based/base.mjs [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+    async deploy() {
+      await this.takeSheetSnapshot(INITIAL_EVENT_COUNT);
+
+      const sheetId = this.getSheetId();
+      const spreadsheet = await this.googleSheets.getSpreadsheet(sheetId);
+      await this.processSpreadsheet(spreadsheet);
+    },
+    async activate() {
+      throw new Error("activate is not implemented");
+    },
```
Comment (michelle0927) [inline components/google_sheets/sources/common/http-based/base.mjs:52]: Since `activate()` is so similar in drive.mjs and sheet.mjs, I think we could put it in base.mjs and use methods `activateHook` in both drive.mjs and sheet.mjs for the call to either `this.googleSheets.activateHook()` or `this.googleSheets.activateFileHook()`.
```suggestion
    async activate() {
      const channelID = this._getChannelID() || uuid();

      const {
        startPageToken,
        expiration,
        resourceId,
      } = await this.activateHook(channelID);

      // Save metadata on the subscription so we can stop / renew later
      // Subscriptions are tied to Google's resourceID, "an opaque value that
      // identifies the watched resource". This value is included in request headers
      this._setSubscription({
        resourceId,
        expiration,
      });
      this._setChannelID(channelID);
      this._setPageToken(startPageToken);

      await this.takeSheetSnapshot();
    },
```

File: components/google_sheets/sources/common/http-based/base.mjs [hunk 4]
```diff
@@ -0,0 +1,141 @@
...
+      : await this.getSpreadsheetToProcess(event);
+
+    if (!spreadsheet) {
+      const sheetId = this.getSheetId();
+      console.log(`Spreadsheet "${sheetId}" was not modified. Skipping event`);
+      return;
+    }
+
+    return this.processSpreadsheet(spreadsheet);
+  },
```
Comment (michelle0927) [inline components/google_sheets/sources/common/http-based/base.mjs:140]: Isn't this overwritten in both drive.mjs and sheet.mjs? I think it could be left out if it isn't being used anywhere.
```suggestion
```

File: components/google_sheets/sources/common/http-based/drive.mjs [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+      this._setSubscription({
+        resourceId,
+        expiration,
+      });
+      this._setChannelID(channelID);
+      this._setPageToken(startPageToken);
+
+      await this.takeSheetSnapshot();
+    },
+  },
```
Comment (michelle0927) [inline components/google_sheets/sources/common/http-based/drive.mjs:57]: If you move the `activate()` hook to base.mjs, this hooks section can be removed.
```suggestion
```

File: components/google_sheets/sources/common/http-based/drive.mjs [hunk 6]
```diff
@@ -0,0 +1,160 @@
...
+  methods: {
+    ...base.methods,
+    _getPageToken() {
+      return this.db.get("pageToken");
+    },
+    _setPageToken(pageToken) {
+      this.db.set("pageToken", pageToken);
+    },
+    async getModifiedSheet(pageToken, driveId, sheetID) {
```
Comment (michelle0927) [inline components/google_sheets/sources/common/http-based/drive.mjs:66]: This would be called from the `activate()` hook in base.mjs
```suggestion
    },
    async activateHook(channelId) {
      return this.googleSheets.activateHook(
        this.http.endpoint,
        this.getDriveId(),
      );
    },
    async getModifiedSheet(pageToken, driveId, sheetID) {
```

File: components/google_sheets/sources/common/http-based/sheet.mjs [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+        expiration,
+      });
+      this._setChannelID(channelID);
+      if (startPageToken) {
+        this._setPageToken(startPageToken);
+      }
+
+      await this.takeSheetSnapshot();
+    },
+  },
```
Comment (michelle0927) [inline components/google_sheets/sources/common/http-based/sheet.mjs:47]: If you move the `activate()` hook to base.mjs, this hooks section can be removed.
```suggestion
```

File: components/google_sheets/sources/common/http-based/sheet.mjs [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+  methods: {
+    ...base.methods,
+    async getAllWorksheetIds(sheetID) {
```
Comment (michelle0927) [inline components/google_sheets/sources/common/http-based/sheet.mjs:50]: This would be called from the `activate()` hook in base.mjs
```suggestion
  methods: {
    ...base.methods,
    async activateHook(channelId) {
      return this.googleSheets.activateFileHook(
        channelID,
        this.http.endpoint,
        this.getSheetId(),
      );
    },
    async getAllWorksheetIds(sheetID) {
```

File: components/google_sheets/sources/common/new-row-added.mjs [hunk 9]
```diff
@@ -0,0 +1,167 @@
...
+  props: {
+    sheetID: {
+      propDefinition: [
+        base.props.googleSheets,
+        "sheetID",
+        (c) => ({
+          driveId: base.methods.getDriveId(c.watchedDrive),
+        }),
+      ],
+    },
```
Comment (michelle0927) [inline components/google_sheets/sources/common/new-row-added.mjs:18]: If you move `sheetID` to base.mjs, this prop can be removed.
```suggestion
```

File: components/google_sheets/sources/common/new-updates.mjs [hunk 10]
```diff
@@ -0,0 +1,221 @@
...
+  props: {
+    sheetID: {
+      propDefinition: [
+        base.props.googleSheets,
+        "sheetID",
+        (c) => ({
+          driveId: base.methods.getDriveId(c.watchedDrive),
+        }),
+      ],
+    },
```
Comment (michelle0927) [inline components/google_sheets/sources/common/new-updates.mjs:19]: If you move `sheetID` to base.mjs, this prop can be removed.
```suggestion
```

File: components/google_sheets/sources/common/new-worksheet.mjs [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+    sheetID: {
+      propDefinition: [
+        base.props.googleSheets,
+        "sheetID",
+        (c) => ({
+          driveId: base.methods.getDriveId(c.watchedDrive),
+        }),
+      ],
+    },
+  },
```
Comment (michelle0927) [inline components/google_sheets/sources/common/new-worksheet.mjs:19]: If you move sheetID to base.mjs, this prop section can be removed.
```suggestion
```

File: components/google_sheets/sources/new-row-added-shared-drive/new-row-added-shared-drive.mjs [hunk 12]
```diff
@@ -0,0 +1,25 @@
...
+  key: "google_sheets-new-row-added-shared-drive",
+  name: "New Row Added (Shared Drive, Instant)",
+  description: "Emit new events each time a row or rows are added to the bottom of a spreadsheet in a shared drive",
+  version: "0.0.1",
+  dedupe: "unique",
+  type: "source",
+  hooks: {
+    ...httpBase.hooks,
+    ...newRowAdded.hooks,
+  },
```
Comment (michelle0927) [inline components/google_sheets/sources/new-row-added-shared-drive/new-row-added-shared-drive.mjs:16]: Since `newRowAdded` doesn't have any hooks, and the hooks from `httpBase` will be included anyway, this hooks section can be eliminated.
```suggestion
```

File: components/google_sheets/sources/new-row-added/new-row-added.mjs [hunk 13]
```diff
@@ -1,172 +1,25 @@
...
-    "Emit new events each time a row or rows are added to the bottom of a spreadsheet",
-  version: "0.0.24",
+  description: "Emit new events each time a row or rows are added to the bottom of a spreadsheet. To use this source with a spreadsheet in a [Shared Drive](https://support.google.com/a/users/answer/9310351), use the **New Row Added (Shared Drive, Instant)** source instead.",
+  version: "0.0.25",
   dedupe: "unique",
   type: "source",
+  hooks: {
+    ...httpBase.hooks,
+    ...newRowAdded.hooks,
+  },
```
Comment (michelle0927) [inline components/google_sheets/sources/new-row-added/new-row-added.mjs:16]: Since `newRowAdded` doesn't have any hooks, and the hooks from `httpBase` will be included anyway, this hooks section can be eliminated.
```suggestion
```

File: components/google_sheets/sources/new-updates-shared-drive/new-updates-shared-drive.mjs [hunk 14]
```diff
@@ -0,0 +1,25 @@
...
+  key: "google_sheets-new-updates-shared-drive",
+  type: "source",
+  name: "New Updates (Shared Drive, Instant)",
+  description: "Emit new event each time a row or cell is updated in a spreadsheet in a shared drive",
+  version: "0.0.1",
+  dedupe: "unique",
+  hooks: {
+    ...httpBase.hooks,
+    ...newUpdates.hooks,
+  },
```
Comment (michelle0927) [inline components/google_sheets/sources/new-updates-shared-drive/new-updates-shared-drive.mjs:16]: Since `newUpdates` doesn't have any hooks, and the hooks from `httpBase` will be included anyway, this hooks section can be eliminated.
```suggestion
```

File: components/google_sheets/sources/new-updates/new-updates.mjs [hunk 15]
```diff
@@ -1,226 +1,25 @@
...
-  description:
-    "Emit new event each time a row or cell is updated in a spreadsheet.",
-  version: "0.0.25",
+  description: "Emit new event each time a row or cell is updated in a spreadsheet. To use this source with a spreadsheet in a [Shared Drive](https://support.google.com/a/users/answer/9310351), use the **New Updates (Shared Drive, Instant)** source instead.",
+  version: "0.0.26",
   dedupe: "unique",
+  hooks: {
+    ...httpBase.hooks,
+    ...newUpdates.hooks,
+  },
```
Comment (michelle0927) [inline components/google_sheets/sources/new-updates/new-updates.mjs:16]: Since `newUpdates` doesn't have any hooks, and the hooks from `httpBase` will be included anyway, this hooks section can be eliminated.
```suggestion
```

**Review by michelle0927 — CHANGES_REQUESTED** [review]

**Comment by jrbrandon** [comment]
When might this be merged? Not trying to rush greatness, just managing my own expectations. Thanks!

**Comment by js07** [comment]
> When might this be merged? Not trying to rush greatness, just managing my own expectations. Thanks!

@jrbrandon The issue has been passed the code review stage and is in the [**Ready for QA column**](https://github.com/PipedreamHQ/pipedream/projects/1#column-14534915) on the Component Backlog project board. The PR should be merged shortly after it has been successfully tested, which should be soon!
