### PR TITLE
Hubspot - add widget props

### LINKED ISSUE #18300: [ACTION] Hubspot Page - Widgets missing from the update page action
**Is there a specific app this action is for?**
In HubSpot pages, widgets are page-level module data that store content directly in templates. They are one of three properties that can be modified via the CMS Pages API:

Widgets are essentially modules or components that can be added to pages to provide specific functionality. HubSpot provides many default widgets/modules including forms, menus, rich text, images, and more. You can also create custom widgets through custom modules.

Many user have custom widgets on their page like forms, associated salesforce campaign IDs, etc. Being able to modify widgets in a page is essential when updating a page

When editing pages via the API, you must include the full definition of widgets when updating them, as partial updates are not supported.

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.hubspot.com/docs/api-reference/legacy/pages-v2/update-Page

### LINKED ISSUE #18306: [BUG] "list pages" in Hubspot always returns empty list
**Describe the bug**
The "list pages" and "list forms" in Hubspot seems to always return empty list. 

**To Reproduce**

1. Create a workflow in pipedream main account
2. Add a node either "list pages" or "list forms" from the HubSpot tool.
3. Enter credentials (I use a developer edition) 
4. Click "Test"
5. Always result in an empty list. Even if i have pages/forms in my account.

**Screenshots**

Image

**Additional context**
I use the hubspot developer edition for testing.

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #18300 
Resolves #18306 

## Summary by CodeRabbit

* **New Features**
  * Create/Update Page and Create/Update Landing Page actions now accept optional widgetContainers and widgets for richer page composition.

* **Chores**
  * Bumped action versions to reflect payload enhancements (including list pages).
  * HubSpot component package version bumped to 1.7.5.

### CODE REVIEW

File: components/hubspot/actions/create-page/create-page.mjs [hunk 1]
```diff
@@ -7,7 +7,7 @@ export default {
   name: "Create Page",
   description:
     "Create a page in HubSpot. [See the documentation](https://developers.hubspot.com/docs/reference/api/cms/pages#post-%2Fcms%2Fv3%2Fpages%2Fsite-pages)",
-  version: "0.0.6",
+  version: "0.0.8",
```
Comment (luancazarine) [inline components/hubspot/actions/create-page/create-page.mjs]:
```suggestion
  version: "0.0.7",
```

Comment (michelle0927) [reply components/hubspot/actions/create-page/create-page.mjs]: Oops, thanks!
