### PR TITLE
HeyGen - New Components

### LINKED ISSUE #9355: [Components] heygen
# heygen
## URLs
- https://docs.heygen.com/reference/authentication-1
#### Prompt
Emit new event when a specific avatar video event occurs. A required prop is a custom set of event(s) that the user wants to trigger.
#### Prompt
Emit new event when a HeyGen video fails during processing. There are no additional props required.
#### Prompt
Emit new event when an avatar video is successfully generated. No additional props are needed.
#### Prompt
Creates a talking photo from a provided image. It requires a 'storage-key' prop which is generated from uploaded image file.
#### Prompt
Generates a video from a selected template. It needs a 'template-id' prop as a required input, indicating the selected template.
#### Prompt
Fetches a shareable link for a specific HeyGen video. It requires a 'video-id' prop referring to the specific HeyGen video.

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #9355 
## WHAT

copilot:summary

copilot:poem

## HOW

copilot:walkthrough

### CODE REVIEW

File: components/heygen/actions/common/video-polling.mjs [hunk 1]
```diff
@@ -0,0 +1,38 @@
+import heygen from "../../heygen.app.mjs";
+
+export default {
+  props: {
+    heygen,
+  },
+  async run({ $ }) {
+    const DELAY = 1000 * 10;
```
Comment (lcaresia) [inline components/heygen/actions/common/video-polling.mjs:8]: Move this to `constants.mjs` file

File: components/heygen/actions/common/video-polling.mjs [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+    const { run } = $.context;
+    if (run.runs === 1) {
+      const videoId = await this.processVideo($);
+      $.flow.rerun(DELAY, {
```
Comment (lcaresia) [inline components/heygen/actions/common/video-polling.mjs:12]:
```suggestion
      $.flow.rerun(constants.DELAY, {
```

**Review by lcaresia — CHANGES_REQUESTED** [review]

**Review by lcaresia — DISMISSED** [review]
LGTM!
