### PR TITLE
Bugfix - Replace File - Google Drive

### LINKED ISSUE #3130: [BUG] Google Drive - Replace File still on v0.0.4 instead of v0.0.5
**Describe the bug**
The latest Google Drive fixes were not released after they were merged:

CleanShot 2022-06-13 at 12 41 25@2x

They should have been updated to `v0.0.5` with this PR merge:

https://github.com/PipedreamHQ/pipedream/pull/3090

@vellames-turing can you investigate?

### PR DESCRIPTION
**Pull request by vellames-turing**
Closes #3130

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

File: components/google_drive/actions/upload-file/upload-file.mjs [hunk 1]
```diff
@@ -88,7 +92,9 @@ export default {
       try {
         const fileBuffer = await streamToBuffer(file);
         const bufferSize = byteToMB(Buffer.byteLength(fileBuffer));
-        uploadType = bufferSize > 5 ? "resumable" : "media";
+        uploadType = bufferSize > 5
+          ? "resumable"
+          : "media";
```
Comment (jcortes) [inline components/google_drive/actions/upload-file/upload-file.mjs:97]: Optional:
Can you import these values from constants?

**Review by jcortes — COMMENTED** [review]
HI @vellames-turing I've just added one minor comment. The resto looks good to me. Thanks. It is ready for QA!
