### PR TITLE
[Salesforce] Enable triggers for Custom Objects

### LINKED ISSUE #4166: [BUG] Can not create Salesforce Instant sources
**Describe the bug**
First reported by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1662346083419929
> Hi All - New to Pipedream. Considering adopting it as core part of our integration stack. However,
it seems I can't create a Salesforce source for instant updates (I have tried this with a few other tools and works just fine so I don't believe its permissions related). Keep getting "Create webook error"
image

The customer also reported that he tried this with [n8n.io](http://n8n.io/), [tray.io](http://tray.io/), and AWS AppFlow, all work with instant style triggers. I've only had this issue with Pipedream.

**To Reproduce**
1. Access Pipedream > Source
2. Create a new Salesforce - New Object (Instant, of Selectable Type)
3. Observe error `UNKNOWN_EXCEPTION: admin operation already in progress`

**Expected behavior**
The source is created successfully.

### PR DESCRIPTION
**Pull request by andrewjschuang**
Enables selection of Custom Objects props in Instant Triggers.

**Notes:**
- [x] Depends on https://github.com/jverce/salesforce-webhooks/pull/16
- [x] Pending `package.json` version bump (and `salesforce-webhooks` package update).
- [x] Pending components version bump.

Resolves #4166.

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4196"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by michelle0927 — APPROVED** [review]
Looks good!

File: components/salesforce_rest_api/sources/common.mjs [hunk 1]
```diff
@@ -13,28 +13,10 @@ export default {
...
-        const { page } = context;
-        if (page !== 0) {
-          return {
-            options: [],
-          };
-        }
-
-        const { sobjects } = await this.salesforce.listSObjectTypes();
-        const options = sobjects
-          .filter(this.isValidSObject)
```
Comment (jverce) [inline components/salesforce_rest_api/sources/common.mjs:29]: Removing this will stop querying Salesforce for the list of available objects in the user's instance. Is this the intention here?

Moreover, querying for updates for some of the objects in Salesforce might not be possible if those objects don't have the `replicateable` flag set (that's what the `.filter` does).

Keep in mind that this particular module/file does not use the webhook approach, so I'm not sure we should even touch this file (unless you have more context and I'm missing something 🤔).

Comment (andrewjschuang) [reply components/salesforce_rest_api/sources/common.mjs:29]: The `propDefinition` part makes it inherit the `async options()` method from the app. The app code is the same as this removed part.

Since you've mentioned this, I've noticed and changed back the label and description for the prop.

File: components/salesforce_rest_api/salesforce_rest_api.app.mjs [hunk 2]
```diff
@@ -23,11 +23,7 @@ export default {
       type: "string",
       label: "SObject Type",
       description: "Standard object type of the record to get field values from",
-      async options(context) {
-        const { page } = context;
-        if (page !== 0) {
-          return [];
-        }
```
Comment (jverce) [inline components/salesforce_rest_api/salesforce_rest_api.app.mjs:30]: Why are we removing the pagination logic?

File: components/salesforce_rest_api/sources/common.mjs (hunk 1 above)
Comment (jverce) [reply components/salesforce_rest_api/sources/common.mjs:29]: I see, so can we also move the `isValidSObject` method to the app module, and replace the hardcoded lambda function in the `.filter` with a call to that method? I'll leave a suggestion in the `.app.mjs` file to reflect this.

File: components/salesforce_rest_api/salesforce_rest_api.app.mjs [hunk 3]
```diff
@@ -201,23 +197,14 @@ export default {
         sobject.name.includes("History")
       );
     },
-    listAllowedSObjectTypes(eventType) {
-      const verbose = true;
-      return SalesforceClient.getAllowedSObjects(eventType, verbose);
-    },
     async createWebhook(endpointUrl, sObjectType, event, secretToken, opts) {
```
Comment (jverce) [inline components/salesforce_rest_api/salesforce_rest_api.app.mjs:200]:
```suggestion
    isValidSObject(sobject) {
      // Only the activity of those SObject types that have the `replicateable`
      // flag set is published via the `getUpdated` API.
      //
      // See the API docs here: https://sforce.co/3gDy3uP
      return sobject.replicateable;
    },
    async createWebhook(endpointUrl, sObjectType, event, secretToken, opts) {
```

**Review by jverce — CHANGES_REQUESTED** [review]

**Comment by dylburger** [comment]
@sweepy84 This is ready for you to test, if you have the time. We can also wrap up the work and publish the new version to production so you can test there - let us know what would work best.

1. Clone the repo locally
2. Check out the PR

Screen Shot 2022-09-15 at 11 02 27 AM

3. [Download and configure the Pipedream CLI](https://pipedream.com/docs/cli/install/)
4. From the repo root, run `pd publish components/salesforce_rest_api/sources/new-object-instant/new-object-instant.mjs`
5. Visit https://pipedream.com/alpha and check the box for **Enable my sources**
6. Visit https://pipedream.com/sources/new , select the option for **My Sources**, and select the Salesforce trigger from there. This should let you create the new version of the trigger.

File: components/salesforce_rest_api/salesforce_rest_api.app.mjs [hunk 4]
```diff
@@ -201,23 +197,14 @@ export default {
...
       const client = this._getSalesforceClient();
       const webhookOpts = {
         endpointUrl,
         sObjectType,
         event,
         secretToken,
-        fieldsToCheck,
-        fieldsToCheckMode,
+        ...opts,
       };
```
Comment (jverce) [inline components/salesforce_rest_api/salesforce_rest_api.app.mjs:208]: We should skip the SObject validation! 😄 
```suggestion
        skipValidation: true,
      };
```

Comment (jverce) [reply components/salesforce_rest_api/salesforce_rest_api.app.mjs:208]: Nevermind, already done here:
https://github.com/PipedreamHQ/pipedream/pull/4196/files/d7402313a6dba44c3f55d0242d94738044c3e430#

**Review by jverce — APPROVED** [review]
LGTM!

File: components/salesforce_rest_api/salesforce_rest_api.app.mjs (hunk 2 above)
Comment (jverce) [reply components/salesforce_rest_api/salesforce_rest_api.app.mjs:30]: I think that without this guard, the user can click the *Load More* button and will get the same list a second time, producing a long list with lots of duplicates.

Comment (andrewjschuang) [reply components/salesforce_rest_api/salesforce_rest_api.app.mjs:30]: I think the UI handles the duplicates, I haven't had this issue and also just teste and it doesn't duplicate the list
